/**
 * Represents a high-level abstraction of complex hardware logic.
 * Generated by Claude when user requests "Simplify" on complex patterns.
 */
export interface Abstraction {
	/** Human-readable name for the abstraction (e.g., "FIFO Controller") */
	name: string;

	/** Description of what this abstraction represents */
	description: string;

	/** Array of high-level blocks/components in this abstraction */
	blocks: AbstractionBlock[];

	/** Array of relationships/connections between blocks */
	relationships: AbstractionRelationship[];

	/** Confidence level (0-1) of the abstraction inference */
	confidence: number;

	/** Original AST node IDs that this abstraction summarizes */
	sourceNodeIds: string[];

	/** Claude's reasoning/explanation for this abstraction */
	reasoning: string;
}

/**
 * Represents a high-level block or component within an abstraction.
 */
export interface AbstractionBlock {
	/** Unique identifier for this block */
	id: string;

	/** Display name of the block */
	label: string;

	/** Type of block (e.g., "controller", "datapath", "state_machine") */
	blockType: string;

	/** Description of what this block does */
	description: string;

	/** Input signals to this block */
	inputs: string[];

	/** Output signals from this block */
	outputs: string[];
}

/**
 * Represents a relationship or connection between abstraction blocks.
 */
export interface AbstractionRelationship {
	/** Source block ID */
	from: string;

	/** Target block ID */
	to: string;

	/** Label describing the relationship (e.g., signal name, control signal) */
	label?: string;

	/** Type of relationship (e.g., "data", "control", "clock") */
	type?: string;
}
